title: Parchment
author: pro-panda
subtitle: The life of a frustrated engineer

url: "https://kutang0.github.io"
baseurl: "/blog"

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr/parchment"
footer_text: "Theme by rhl-bthra"

profile-picture: assets/profile-theo.jpeg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://www.dropbox.com/scl/fi/v402pl41iso043xjuaj6p/Resume.pdf?rlkey=3dlqj7nwwjawehai5ps68bs4f&e=1&st=hyet4rn1&dl=0"
